server:
  port: 10080
spring:
  application:
    name: service-search   #服务名
  elasticsearch:
    rest:
      uris: 101.43.63.144:9200
  cloud: #注册到Nacos
    nacos:
      discovery:
        server-addr: 101.43.63.144:8848
