server:
  port: 10090
spring:
  application:
    name: service-order  #服务名
  cloud: #注册到Nacos
    nacos:
      discovery:
        server-addr: 101.43.63.144:8848
#    alibaba:
#      seata:
#        tx-service-group: fsp_tx_group #这里和file.conf中事务组名一样
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://101.43.63.144:3306/ymcc_order?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 101.43.63.144
    port: 6379
    jedis:
      pool:
        max-wait: 2000ms
        min-idle: 2
        max-idle: 8
#seata:
#  enableAutoDataSourceProxy: false #关闭DataSource代理的自动配置，我们要手动配置
seata:
  service:
    vgroupMapping:
      fsp_tx_group: default
    grouplist:
      default: 101.43.63.144:8091
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/cn/lzs/ymcc/mapper/*.xml #加载读取mapper.xml文件的位置


rocketmq:
  name-server: 101.43.63.144:9876
  #生产者配置
  producer:
    #生产者组名字
    group: "service-order-producer"
    # 消息最大长度 默认 1024 * 4 (4M)
    max-message-size: 4096
    # 发送消息超时时间，默认 3000
    send-message-timeout: 3000
    # 发送消息失败重试次数，默认2
    retry-times-when-send-failed: 2
    retry-times-when-send-async-failed: 2
