#java???????: mapper,service,controller
OutputDir=D:/SpringCode/lzs-ymcc/ymcc-service/ymcc-service-common/src/main/java

#mapper.xml
OutputDirXml=D:/SpringCode/lzs-ymcc/ymcc-service/ymcc-service-common/src/main/resources

# domain,query
OutputDirBase=D:/SpringCode/lzs-ymcc/ymcc-pojo/ymcc-pojo-common/src/main/java

#??
author=lzs

#?????
parent=cn.lzs.ymcc

#???
jdbc.driver=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql:///ymcc_common?serverTimezone=UTC
jdbc.user=root
jdbc.pwd=123456